### ISSUE TITLE
pip安装robotframework-appiumlibrary时报错

### ISSUE THREAD

**Issue by mzky** [small99/AutoLink#11]
通过 pip install -r requirements.txt安装报错
![9](https://user-images.githubusercontent.com/13345233/45534915-424b3980-b82f-11e8-8831-2dee477d05b8.png)

linux问题相同
![0](https://user-images.githubusercontent.com/13345233/45534987-7f173080-b82f-11e8-8707-b7e1aac91ac3.png)

加上--trusted-host pypi.org参数后问题已解决
pip install --trusted-host pypi.org -r requirements.txt

**Comment by mzky** [comment]
补充下无错安装命令：
python -m pip install --upgrade pip
pip install pytest-runner
pip install --trusted-host pypi.org --trusted-host pypi.python.org -r requirements.txt

备注：pytest-runner插件用python install安装不上，用pip正常

**Comment by small99** [comment]
这是你本地python相关环境的问题，不够新， autolink基于3.6进行开发的，最好把本地环境进行更新
