### ISSUE TITLE
调度任务状态显示

### ISSUE THREAD

**Issue by wck821829906** [small99/AutoLink#4]
@small99 能否增加一个调度任务的状态显示，比如“执行中/执行失败/执行挂起”等状态显示

**Comment by small99** [comment]
在左边树控件，任一项目名称上右击选择"查看任务"， 在该项目的任务列表，看最左边的图标，有四种状态：执行中、成功、异常、失败

**Comment by wck821829906** [comment]
你好，可以加入AutoLink交流群么？交流一下

发自我的 iPhone

**Comment by small99** [comment]
加微信 liyimin1912  入群
